# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 1337 H4x with j33m
email: jeem@j33m.net
description: > # this means to ignore newlines until "baseurl:"
  This is where I record my progress on random projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://j33m.net" # the base hostname & protocol for your site

github_username:  gilderjw 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

port: 8080

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

encoding: utf-8
pagenate: 3
